# Generated by Django 4.2.3 on 2023-07-17 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageFront",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=30)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("screen", models.CharField(max_length=20)),
                ("event", models.CharField(max_length=20)),
            ],
        ),
    ]
