# Generated by Django 4.2.3 on 2023-07-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pril", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=30)),
                ("keywisper", models.CharField(max_length=50)),
            ],
        ),
    ]
