# Generated by Django 4.2.3 on 2023-07-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pril", "0002_userkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagefront",
            name="key",
            field=models.CharField(default="", max_length=50),
        ),
    ]
