# Generated by Django 4.2.3 on 2023-07-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pril", "0003_messagefront_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserKeyCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counter", models.IntegerField(default=0)),
                (
                    "user_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userkeycounter",
                        to="pril.userkey",
                    ),
                ),
            ],
        ),
    ]
